### ISSUE TITLE
Add intake and Eject state to shooter

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#35]
While intaking, the shooter feed motor needs to run backward to hold balls in place. Add this state as a possible state of the shooter, and add logic to spin it backward when in the intake state.

Same thing for eject - the shooter motor should not run, but the feeder motor should run in a direction which ejects the ball

**Comment by imdunne8** [comment]
Add an enum called `shooterFeedCmdState` in Shooter.java that looks similar to this one from Intake.java:
```
    public enum intakeCmdState{
        STOP(0),
        INTAKE(1),
        EJECT(-1);


        public final int value;


        private intakeCmdState(int value) {
            this.value = value;
        }


        public int toInt() {
            return this.value;
        }
    }
```
It should have states `STOP`, `INTAKE`, `FEED`, and `EJECT`.  Then modify the `setFeed` method to take in a `shooterFeedCmdState` rather than a boolean and the `feed_Cmd` variable should be changed to a `shooterFeedCmdState` as well.  Handle each possible state similar to how it is done in Intake.java, with a calibration for each (one already exists for `feedSpeed`).  The `update()` method will then need to be updated to handle each state.
