### ISSUE TITLE
Photonvision - set up a red/blue cargo processing pipeline

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2022#9]
Set up a vision processing pipeline in photonvision to detect spherical red/blue blobs. Add logic in robot code to return this information in a class method.

screenshot the settings and put there here for reference

**Comment by imdunne8** [comment]
One alternative is Axon if someone wants to try it:
Follow instructions for setup [here](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/axon/inferencing-on-a-raspberry-pi.html)
For the "Uploading the Model to the Pi" step, use [this zip file](https://drive.google.com/file/d/1iG52wQsNz-ovmTQkSJoe-BZo2aAQgA7i/view?usp=sharing)
Then otherwise follow along.  It should "just work", but at 4-5fps.
